@TodoApp.API_HostAddress = https://localhost:5001

GET {{TodoApp.API_HostAddress}}/todos

###

GET {{TodoApp.API_HostAddress}}/todos/1

###

GET {{TodoApp.API_HostAddress}}/todos/complete

###

POST {{TodoApp.API_HostAddress}}/todos
Content-Type: application/json

{
    "name": "Need to go to Market"
}
###


PUT {{TodoApp.API_HostAddress}}/todos/1
Content-Type: application/json

{
    "name": "Need to go to Gym",
    "isCompleted": true
}

###

DELETE {{TodoApp.API_HostAddress}}/todos/1

###
